# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\scoreboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(545, 347)
        Form.setStyleSheet("QWidget{\n"
"    background-image: url(:/scoreboards/scoreboard/scr_brd (1).jpg);\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(150, 130, 261, 101))
        self.frame.setStyleSheet("QFrame{\n"
"    border-radius: 20px;\n"
"    border: 2px solid rgba(255, 255, 255, 180);\n"
"    background: rgba(255, 255, 255, 140);\n"
"}\n"
"QLabel{\n"
"    background: #fff;\n"
"    border-radius: 30px;\n"
"    border: 2px solid gray;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(60, 60))
        self.label_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: red;\n"
"    border-color: red;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(60, 60))
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: blue;\n"
"    border-color: blue;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Scoreboard"))
        self.label_3.setText(_translate("Form", "<html>\n"
"    <head/>\n"
"    <body>\n"
"        <p style=\"font-size: 18px; padding: 0px; margin: 0px;\">\n"
"            {}\n"
"        </p>\n"
"        <p style=\"font-size: 8px; padding: 0px; margin: 0px;\">\n"
"            Player 1\n"
"        </p>\n"
"    </body>\n"
"</html>"))
        self.label_2.setText(_translate("Form", "<html>\n"
"    <head/>\n"
"    <body>\n"
"        <p style=\"font-size: 18px; padding: 0px; margin: 0px;\">\n"
"            {}\n"
"        </p>\n"
"        <p style=\"font-size: 8px; padding: 0px; margin: 0px;\">\n"
"            Player 1\n"
"        </p>\n"
"    </body>\n"
"</html>"))
import assets_rc
